/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@1.31.1.
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type * as chats from "../chats.js";
import type * as conversations from "../conversations.js";
import type * as datarooms from "../datarooms.js";
import type * as documents from "../documents.js";
import type * as links from "../links.js";
import type * as tags from "../tags.js";
import type * as teams from "../teams.js";
import type * as users from "../users.js";
import type * as views from "../views.js";
import type * as webhooks from "../webhooks.js";
import type * as workflows from "../workflows.js";

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";

/**
 * A utility for referencing Convex functions in your app's API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
declare const fullApi: ApiFromModules<{
  chats: typeof chats;
  conversations: typeof conversations;
  datarooms: typeof datarooms;
  documents: typeof documents;
  links: typeof links;
  tags: typeof tags;
  teams: typeof teams;
  users: typeof users;
  views: typeof views;
  webhooks: typeof webhooks;
  workflows: typeof workflows;
}>;
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;
