/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS FILE IS AUTO-GENERATED by Convex dev server.
 *
 * For testing, this is a stub file. Run `npx convex dev` to generate the real file.
 *
 * @module
 */

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";

import type * as users from "../users.js";
import type * as teams from "../teams.js";
import type * as documents from "../documents.js";
import type * as links from "../links.js";
import type * as views from "../views.js";
import type * as datarooms from "../datarooms.js";
import type * as conversations from "../conversations.js";
import type * as chats from "../chats.js";
import type * as workflows from "../workflows.js";
import type * as webhooks from "../webhooks.js";
import type * as tags from "../tags.js";
import type * as actions_storage from "../actions/storage.js";
import type * as actions_email from "../actions/email.js";
import type * as actions_stripe from "../actions/stripe.js";

/**
 * A utility for referencing Convex functions in your app's API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
declare const fullApi: ApiFromModules<{
  users: typeof users;
  teams: typeof teams;
  documents: typeof documents;
  links: typeof links;
  views: typeof views;
  datarooms: typeof datarooms;
  conversations: typeof conversations;
  chats: typeof chats;
  workflows: typeof workflows;
  webhooks: typeof webhooks;
  tags: typeof tags;
  "actions/storage": typeof actions_storage;
  "actions/email": typeof actions_email;
  "actions/stripe": typeof actions_stripe;
}>;

export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;
