/* eslint-disable */
/**
 * Generated data model types.
 *
 * THIS FILE IS AUTO-GENERATED by Convex dev server.
 *
 * For testing, this is a stub file. Run `npx convex dev` to generate the real file.
 *
 * @module
 */

import type { DataModelFromSchemaDefinition } from "convex/server";
import type { DocumentByInfo, GenericId } from "convex/values";
import type schema from "../schema.js";

/**
 * The names of all of your Convex tables.
 */
export type TableNames = keyof DataModel;

/**
 * The type of a document stored in Convex.
 */
export type Doc<TableName extends TableNames> = DocumentByInfo<
  DataModel[TableName]
>;

/**
 * An identifier for a document in Convex.
 *
 * Convex documents are uniquely identified by their `Id`, which is accessible
 * on the `_id` field. To learn more, see [Document IDs](https://docs.convex.dev/using/document-ids).
 *
 * Documents can be loaded using `db.get(id)` in query and mutation functions.
 *
 * IDs are just strings at runtime, but this type can be used to distinguish them from other
 * strings when type checking.
 */
export type Id<TableName extends TableNames> = GenericId<TableName>;

/**
 * A type describing your Convex data model.
 *
 * This type includes information about what tables you have, the type of
 * documents stored in those tables, and the indexes defined on them.
 *
 * This type is used to type the methods and properties of the Convex
 * database context.
 */
export type DataModel = DataModelFromSchemaDefinition<typeof schema>;
